import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideIcons } from '@ng-icons/core';
import {
  heroFingerPrint,
  heroPhone,
  heroUser,
  heroTrophy,
  heroCreditCard,
  heroArrowRight,
  heroChevronDown,
  heroUserGroup,
  heroCheckCircle,
  heroClock,
  heroMagnifyingGlass,
  heroFunnel,
  heroArrowDownTray,
  heroRectangleGroup,
  heroEllipsisVertical,
  heroChevronLeft,
  heroChevronRight,
  heroInformationCircle,
  heroRectangleStack,
  heroCalendar,
  heroCog6Tooth,
  heroBookmark,
  heroPlus,
  heroTrash,
  heroWifi,
  heroBell,
  heroSignal,
  heroPencilSquare,
  heroExclamationTriangle,
  heroPaperAirplane,
  heroFlag,
  heroSquares2x2,
  heroChartBar,
  heroXMark,
  heroChatBubbleLeftRight,
  heroSun,
  heroMegaphone
} from '@ng-icons/heroicons/outline';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideIcons({
      heroFingerPrint,
      heroPhone,
      heroUser,
      heroTrophy,
      heroCreditCard,
      heroArrowRight,
      heroChevronDown,
      heroUserGroup,
      heroCheckCircle,
      heroClock,
      heroMagnifyingGlass,
      heroFunnel,
      heroArrowDownTray,
      heroRectangleGroup,
      heroEllipsisVertical,
      heroChevronLeft,
      heroChevronRight,
      heroInformationCircle,
      heroRectangleStack,
      heroCalendar,
      heroCog6Tooth,
      heroBookmark,
      heroPlus,
      heroTrash,
      heroWifi,
      heroBell,
      heroSignal,
      heroPencilSquare,
      heroExclamationTriangle,
      heroPaperAirplane,
      heroFlag,
      heroSquares2x2,
      heroChartBar,
      heroXMark,
      heroChatBubbleLeftRight,
      heroSun,
      heroMegaphone
    })
  ]
};
